### ISSUE TITLE
provided.placeholder in a table

### ISSUE THREAD

**Issue by valmassoi** [atlassian/react-beautiful-dnd#103] opened 2017-09-19 22:26 UTC
To add the `provided.placeholder` for a table row the `tr` and `provided.placeholder` need to be wrapped in a div but this messes up the rows format. Any recommendations on what to do here?

```jsx
<tbody>
rowList.map((key) => (
    <Draggable
        key={key}
        draggableId={key}
    >
        {(provided, snapshot) => (
            <div> // need to wrap in div to add the placeholder
                <tr>...</tr>
                {provided.placeholder}
            </div>
        ))}
    </Draggable>
)
</tbody>
```

**Comment by alexreardon** [comment] 2017-09-19 23:50
You would try wrapping the placeholder in a `<tr>`. Let me know how you go

**Comment by valmassoi** [comment] 2017-09-19 23:58
The problem is my normal <tr> being wrapped by a div even without the placeholder or this package in general the extra div screws up the table

**Comment by alexreardon** [comment] 2017-09-20 00:32
Oh sorry, this is for the `Draggable`. I am following now. Yes, the current API does make this hard. We need the `provided.placeholder` to be a sibling of the element which cannot currently do as `React` does not support returning an array of children. Once we move to React 16 we will be able to overcome this limitation: (see https://github.com/facebook/react/issues/2127) for more details.

Can you please create an example on webpack bin with this scenario? That way we can have a play and see if there is a reasonable workaround in the meantime. Here is a base for you to get started with: https://www.webpackbin.com/bins/-Kr9aE9jnUeWlphY8wsw

**Comment by valmassoi** [comment] 2017-09-20 17:28
@alexreardon here's the example with tables: https://www.webpackbin.com/bins/-KuVEVD2KOW8uNkxiBWa
Try deleting the three lines that say comment out - this will change it to proper table formatting but loses the placeholder

**Comment by alexreardon** [comment] 2017-09-20 20:43
Unfortunately this is a current limitation of React:
https://www.webpackbin.com/bins/-KuW-9jwJpDYOuX1Yjrb

I cannot seem to find a way to return an array

**Comment by alexreardon** [comment] 2017-09-20 20:44
Caused by #8

**Comment by alexreardon** [comment] 2017-09-20 20:44
I am keen to get this working - as we too will need sortable tables!

**Comment by alexreardon** [comment] 2017-09-20 20:44
For now i'll close this as a duplicate and track it in #8 .

**Closed by alexreardon** 2017-09-20 20:44 UTC
Labels: question

**Comment by valmassoi** [comment] 2017-09-20 21:12
Ok thanks Alex. I'm thinking about trying to hack a placeholder by adding a temporary row with empty data to my array that gets mapped to build the `tr`s when `onDragStart` fires and remove it when `onDragEnd` and I'll splice it in at the `source.index` with a class to make it transparent.

Another problem I found with the table is when dragging the row loses its auto width:
<img width="733" alt="screen shot 2017-09-20 at 15 10 06" src="https://user-images.githubusercontent.com/17240764/30667792-f2a9f60c-9e15-11e7-932b-5a23ec5f9499.png">
`AUY.DLR` is being dragged and the `$0.0010 x 1,300` should be under the `Ask` Col

**Comment by alexreardon** [comment] 2017-09-21 01:07
Without seeing the source it is a little tricky to know what is going on. Can you mimic your example in webpack bin so i can take a look?

**Comment by valmassoi** [comment] 2017-09-29 15:53
@alexreardon the placeholder is working in react 16! 
https://www.webpackbin.com/bins/-KvDK5REuF8Lzp0oT5Hk
and now you can see the table row width issue when dragging

**Comment by jaredcrowe** [comment] 2017-10-02 22:22
nice one @valmassoi!

I don't think there's much we can do about the table column widths if you need to use `table-layout: auto`. We set `position: fixed` on the dragging item, which pulls it out of the flow so the column widths will collapse. The simple work-around is to hard-code table and column widths, like so: https://www.webpackbin.com/bins/-KvU70fxM3VdlP_ND0Zv.

A more complicated work-around could be to read the width of the table columns on drag start and manually set the column widths on the dragging item. I haven't tested this solution, but I assume it'd work?

**Comment by Geeman201** [comment] 2018-03-24 13:52
I just came across the same issue and as webpackbin has merged with codesandbox had to do a few things to get the examples above working thought I'd share @valmassoi's example above for anyone who needs it:

https://codesandbox.io/s/32yrn7nj6p
