### ISSUE TITLE
Draggable gets stuck at the border while dragging above an iframe

### ISSUE THREAD

**Issue by jackrussell1996** [atlassian/react-beautiful-dnd#2159] opened 2021-03-26 21:07 UTC
### Expected behavior
a Draggable from a parent frame should stay with the cursor while dragging above an iframe
### Actual behavior
a Draggable from a parent frame gets stuck at the border while dragging above an iframe

### Steps to reproduce

drag a draggable from a parent frame over an iframe

### What version of `React` are you using?

16.13.1

### What version of `react-beautiful-dnd` are you running?

13.0.0

### What browser are you using?

Chrome 89.0.4389.90 MacOS

### Demo

https://codesandbox.io/s/draggables-cannot-be-dragged-over-iframe-nmsq2

**Comment by danieldelcore** [comment] 2021-03-31 05:39
Hi there, this behaviour is caused by the way event bubbling works with iframes. There's not much we can do from within this library, however you might be able to configure something yourself with the iframe. 

Here are a few pages I found that describe the problem and  possible workarounds:
- https://www.gyrocode.com/articles/how-to-detect-mousemove-event-over-iframe-element/
- https://stackoverflow.com/questions/5645485/detect-mousemove-when-over-an-iframe/11865037#11865037

Will close this issue for now, but please feel free to reopen if you think the problem exists within the library, thanks!

**Closed by danieldelcore** 2021-03-31 05:39 UTC
Labels: 3rd party integration :handshake:

**Comment by jackrussell1996** [comment] 2021-04-28 18:24
Since mutating iframes in the page was concerning - I went with this approach:

```typescript
const { documentElement } = document;
let capturedPointerId: PointerEvent["pointerId"];

const documentPointerMoveOnceListener = ({ pointerId }: PointerEvent) => {
  document.removeEventListener("pointermove", documentPointerMoveOnceListener);
  capturedPointerId = pointerId;
  documentElement.setPointerCapture(capturedPointerId);
};

export const setDocumentPointerCapture = () => {
  document.addEventListener("pointermove", documentPointerMoveOnceListener);
};

export const releaseDocumentPointerCapture = () => {
  if (capturedPointerId) {
    documentElement.releasePointerCapture(capturedPointerId);
  }
};
```

This does however make for a leaky abstraction - If there is interest/support where would I start for adding this to rbd?
