### ISSUE TITLE
Initial drag lag

### ISSUE THREAD

**Issue by vladimir-konnov** [atlassian/react-beautiful-dnd#587] opened 2018-06-27 14:20 UTC
## Bug or feature request?
(answer here)
Bug

When I update the page and do the first drag the kanban card is dragged and drawn with the lag (see https://monosnap.com/file/OsE7E51YHpoC05jlRV7grtPjDnbH1l)
For the second and third (and further) drags everything works fine, but after I refresh the page and do another first drag on the fresh page it happens again: dragged card is drawn aside from cursor.
Where should I dig to? I mean what might be the problem here? Capturing the dimensions or just give another `render` to the card and it's gonna be drawn fine?

I don't get what may be the difference between 'first' drag and other drags here? Mounting components? Why it's drawn aside/away for the first time? I'm clueless about where to look into now.

Upd: I found out that it happens not only on first drag, but mostly on first drag. In your examples (board large data set), when I drag an item the card follows the mouse pointer and even if there's a lag, the card always 'chases' the mouse pointer.

Thank you, any advice will be appreciated.

### Expected behavior
Mouse pointer should be where user first clicked on the card
### Actual behavior
Card is drawn away from the mouse pointer
### Steps to reproduce
Drag a card for the first time on page
### What version of `React` are you using?
16.4.1

### What version of `react-beautiful-dnd` are you running?
4.0.1

### What browser are you using?
Chrome 67.0.3396.79 (64 bit) (Mac or Windows -- both OSs)

### Demo
https://monosnap.com/file/OsE7E51YHpoC05jlRV7grtPjDnbH1l

**Comment by alexreardon** [comment] 2018-06-27 20:10
Firstly, try upgrading to the latest version of react-beautiful-dnd

**Comment by vladimir-konnov** [comment] 2018-06-27 20:18
I can't: there's autoscroll feature that breaks completely valid scroll behavior on page: after user scroll the coordinates of dropables aren't recalculated, so hover doesn't work properly anymore (until scrolled back).
And I cannot optionally turn on/off autoscroll feature https://github.com/atlassian/react-beautiful-dnd/issues/460 :(

**Comment by alexreardon** [comment] 2018-06-27 21:42
Sounds like you are using nested scroll contains which are not supported
yet. The auto scroll is not the issue. If you scroll with a mouse wheel
while a drag is occurring you will see the same thing.

At this stage we are not supporting old versions of he library in order to
focus on moving this forward

**Comment by alexreardon** [comment] 2018-06-28 00:16
So I know, how many items are in each list?

**Comment by alexreardon** [comment] 2018-06-28 00:18
Try upgrading and see if that solves the issue

**Comment by vladimir-konnov** [comment] 2018-06-28 13:10
>  If you scroll with a mouse wheel while a drag is occurring you will see the same thing.
Yes, you're right. It doesn't work when I scroll while dragging. The problem with upgrade was that even when I block scrolling by mouse and keyboard, autoscrolling does the scroll (when moving acard downwards the container bottom) despite my blockage. That's why I couldn't upgrade, and that's why I wanted autoscroll to be optional
> So I know, how many items are in each list?
Initially 6 cards in a list, but then page-by-page there may be 6xN cards in each list.

**Comment by vladimir-konnov** [comment] 2018-06-28 22:16
@alexreardon I'm following your advice about upgrading the version and I upgraded it to the latest one 7.1.3. But it doesn't seem to help, I reproduced this issue in your examples page
https://monosnap.com/file/eKiGsaf0lRAvOiZliWhkFi6tYZWsck
Also after upgrade I came across another issue now: card is 'hidden' behind another card when I'm dragging a card over other cards https://monosnap.com/file/tD06trkn4aEXV1dTTEe4pLNm3P5eW5
Now I have 2 questions to discuss:
1. What might be the root cause of the lag issue in the first video? Browser? Or some timeouts (or maybe smth else) in dnd library code and hence wrong coordinates in the dragged card and mouse pointer?
2. Why a card might get hidden behind another card while hovering? Do I need to specify some particular css properties on a card component (or card container component)?

So the first issue is a general one and doesn't depend on my code. I hope we can find out why it may happen.
And the second one might be related to dnd library changes which I haven't yet faced and implemented during upgrade. The rest of the library looks very good after upgrade. But I cannot finish upgrading unless I fix the latest issue with hidden cards. Could you please advise on that?

**Comment by alexreardon** [comment] 2018-07-02 03:58
Can you please create a new issue for the layering issue you are experiencing? Otherwise, things will get messy here.

I'll see if i can take a look into the initial lag

**Comment by alexreardon** [comment] 2018-07-04 01:30
Regarding the initial lag issue @vladimir-konnov, can you please upgrade to 8.0 and let me know if you are still experiencing it?

**Comment by vladimir-konnov** [comment] 2018-07-06 00:12
@alexreardon tried to upgrade to v8.0.1. It looks way better, but I managed to reproduce the issue on the examples page https://monosnap.com/file/gcdBokOlHal5CknKTCUKsuRmLCXjTu. I don't know the version you have there, but I hope it's the latest one.
Also I noticed an error in dev. console ``Trying to set droppable isEnabled to false but it is already false`` which breaks component updates and stops the drag operation https://monosnap.com/file/Xxcz3D4f5TmW0A8ewGZNsxDjQjSBEa
I'm longing for scrollable containers support, because with scroll other droppable areas don't detect hover correctly if their coordinates changed after drag started. Hover is detected correctly only when dragging over initial coordinates https://monosnap.com/file/ANFS3WK9Y5oehMv1edDb4K0LKjIs6n
P.S. layering issue seems to be gone, at least I couldn't reproduce it, because all cards below the possible drop place are moved down and no card was 'hidden' behind other cards.

**Comment by alexreardon** [comment] 2018-07-06 04:21
It looks like there is some interesting things going on there. It is hard to action these. Can you please split out your various issues into separate github issues - ideally with a reproducible example. Without that it is hard for us to know what is going on

**Comment by alexreardon** [comment] 2018-07-09 06:12
Hi @vladimir-konnov,

Thank you for reaching out in order to improve this project. However, in its current state this issue cannot really be actioned. I will close this issue for now as it sounds like the initial issue is gone. If there are still other problems you are having please be encouraged to create separate issues for them. We also need independent examples to be able to action anything as otherwise we cannot know what your setup is.

Cheers

**Closed by alexreardon** 2018-07-09 06:12 UTC
Labels: more information required

**Comment by barrychapman** [comment] 2020-10-16 04:19
This issue is still here, it seems to be a delay between when the mouse is clicked on the Handle of the draggable and when it actually locks.

If you click on the draggable, and then wait about half a second before dragging, you will see the following behaviours:

**Case 1: Click and immediate drag**

https://www.screencast.com/t/h7F59p4IJz

**Case 2: Click and pause for about 1 second, then drag**

https://www.screencast.com/t/fbVL0PdtM

I hope this helps. It seems that there is some kind of lock delay between when the mouse is clicked on whatever handle or draggable is, and when the mouse starts movement with the draggable.

Hope this helps
