### ISSUE TITLE
Accessing nonexistent addons channel

### ISSUE THREAD

**Issue by HazemEngMuh** [atlassian/react-beautiful-dnd#390] opened 2018-03-16 13:16 UTC
Suddenly when I drag and drop cardView board shows this error 
My package.json:

    "@storybook/addon-actions": "^3.3.11",
    "@storybook/addons": "^3.3.11",
    "@storybook/react": "^3.3.11",  
    "react-beautiful-dnd": "^4.0.1",
    "styled-components": "^3.0.2"

Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel

Board._this.onDragStart
C:/WORKSPACE/web/src/plugins/TaskTracking/Board/board.jsx:73
  ` onDragStart = (initial: DragStart) => {
   console.log('initial onDragStart', initial)
    publishOnDragStart(initial)
    this.setState({
      autoFocusTaskCardId: null})
`
   Does any  one have stable versions ??

**Comment by alexreardon** [comment] 2018-03-20 21:38
I am not sure what the issue is. I suspect it is a storybook issue and not to do with this project.

If you would like us to look at this further please create a stand alone example for us

**Comment by HazemEngMuh** [comment] 2018-03-21 06:55
you can see my example from here:
https://github.com/HazemEngMuh/ReactDNDStorybookIntegration
My problem is when i move QuoteItem from a column to another column I face this error 
Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel

I have integrated storybook with my project successfully but I can't solve this problem

**Comment by alexreardon** [comment] 2018-03-21 07:51
From what I can tell this issue is not related to `react-beautiful-dnd`. I cannot see where your stories are. Can you please provide the path to your failing example?

**Comment by HazemEngMuh** [comment] 2018-03-21 07:59
I used board as   <Board initial={data.medium} containerHeight='60vh' /> in
https://github.com/HazemEngMuh/ReactDNDStorybookIntegration/blob/master/src/App.js

without stories method and was working fine but suddenly QuoteItems moving not works in board

**Comment by HazemEngMuh** [comment] 2018-03-21 08:09
After integration story book I have added 
```
 "@storybook/addon-actions": "^3.3.11",
    "@storybook/addons": "^3.3.11"
```
Now works fine but Do I use a correct way ??

**Comment by alexreardon** [comment] 2018-04-14 03:02
I suspect so? I'm going to close this now as there is nothing to action here

**Closed by alexreardon** 2018-04-14 03:02 UTC
Labels: more information required
