### ISSUE TITLE
Scrolling draggable items on iOS broken since 11.0.0

### ISSUE THREAD

**Issue by gavrichards** [atlassian/react-beautiful-dnd#1396] opened 2019-07-08 08:25 UTC
We have a Trello-style application, with columns which you can scroll horizontally, and each column containing items you can scroll vertically. You can drag items up and down columns and from one column to another.

This has all worked perfectly well until upgrading from 10.1.1 to 11.0.0 or above.

We are now finding that on iOS (either Safari or Chrome) you cannot scroll either horizontally or vertically by dragging your finger on the items in the columns. If you drag/scroll the column header, where no items are located, you can still scroll the columns horizontally, leading me to think it is some functionality of the draggable items that is interfering with the scrolling. 

The drag handle of the items in the columns is the entire item, so almost all of each column is a draggable surface. The drag handle of the columns themselves is only a small handle in the top left corner of each column, so there is space to the right of the handle which isn't 'draggable' where you can scroll the columns horizontally.

To be clear - this problem is not about dragging items and auto scrolling their container while dragging - this is about scrolling the container itself without dragging anything.

Did something change in v11 which would affect this behaviour?

**Comment by alexreardon** [comment] 2019-07-09 05:49
I cannot seem to reproduce the issue

**Comment by alexreardon** [comment] 2019-07-09 05:49
Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

**Comment by alexreardon** [comment] 2019-07-09 05:50
I just checked and I was able to reproduce this :|

**Comment by alexreardon** [comment] 2019-07-09 05:52
I can also confirm this is occurring in `12.x`

**Comment by alexreardon** [comment] 2019-07-09 07:02
It has to do with our force press opt out. 

If you change `shouldRespectForcePress` to `true` then everything should start working again

**Comment by gavrichards** [comment] 2019-07-09 07:58
I'll give that a try @alexreardon. Is this expected behaviour? Or is changing `shouldRespectForcePress` a temporary solution?

**Comment by alexreardon** [comment] 2019-07-09 09:28
it is a temporary solution. i can see that the issue is with that behaviour

**Comment by gavrichards** [comment] 2019-07-09 09:44
Thanks. I think we'll stick on `10.1.1` for now until there is a fix.

**Comment by alexreardon** [comment] 2019-07-09 10:07
Can you please verify if that change works for you?

**Comment by gavrichards** [comment] 2019-07-09 10:29
@alexreardon I've upgraded to `11.0.4` and added `showRespectForcePress={true}` to my Draggables and scrolling is still not working.

**Comment by alexreardon** [comment] 2019-07-10 04:19
I am investigating this now

**Comment by alexreardon** [comment] 2019-07-10 06:00
https://bugs.webkit.org/show_bug.cgi?id=199658

**Comment by alexreardon** [comment] 2019-07-11 22:32
I have shipped the workaround in an alpha for validation: 

`12.0.0-alpha.7`

Please try it out and let me know how it goes

**Comment by moubi** [comment] 2019-07-19 12:22
@alexreardon I can confirm that the fix in `12.0.0-alpha.7` does fix the issue for me.

**Comment by alexreardon** [comment] 2019-07-22 01:31
Fixed in `11.0.5`

**Closed by alexreardon** 2019-07-22 01:31 UTC
Labels: bug 🐞, investigating 🕵️‍♂️
