### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by enapupe** [atlassian/react-beautiful-dnd#568] opened 2018-06-22 17:12 UTC
I was just looking into `react-beautiful-dnd`'s dependencies and realized most of them are already used in my project, I went checking for the bundle size impact and realized it increased almost 100% (100% being a standalone install with all deps), but I was already linking most of the dependencies!

Webpack was was duplicating the deps because version miss-match (sometimes just a patch version ahead/behind).
These are the deps I already had and were installed again (in duplicity):

```
➜ ls node_modules/react-beautiful-dnd/node_modules 
babel-runtime            lodash        react-redux  regenerator-runtime
fbjs                     lodash-es     redux        reselect
hoist-non-react-statics  react-motion  redux-thunk  symbol-observable
```

After checking package dependencies version and updating some of my own, this is the end result I got:

```
➜ ls node_modules/react-beautiful-dnd/node_modules
babel-runtime  regenerator-runtime
```

My initial (before installing this package) vendor bundle was **717 kb** (non-gz), after installing `react-beaituful-dnd` carelessly, it went up to **858 kb**, after matching dependencies I got it down to **815 kb**.

Is there a chance to have maybe a release with more loose dependecy lock? That would mean some people having bugs because of deps mismatching but mostly I'm guessing people would save some kbs from their bundle.

For instance, I was bundling `react-redux` twice because mine was `^5.0.6` and yours `^5.0.7`, the same happened with `redux-thunk`, two minor releases behind - these minor were related to TypeScript so no API actually changed there...

Thanks for you time and many thanks for the library, it's beautiful indeed.

**Comment by TrySound** [comment] 2018-06-22 17:30
@enapupe Dependencies are not locked. If you use yarn then run `yarn upgrade-interactive` and select dependencies you would like to upgrade.
https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L47-L57

**Comment by enapupe** [comment] 2018-06-22 17:37
I understand they are not "locked" per se, but most of the times a dev will just run `yarn add react-beautiful-dnd` and have necessary dependencies installed, like happened to me. Having a wider range of versions would have prevented that from happening, automatically.

**Comment by TrySound** [comment] 2018-06-22 17:40
They are wide enough. minor and patch are taked automatically per semver. The problem is that your dependency are locked and you should upgrade them on your side.

**Comment by enapupe** [comment] 2018-06-22 18:32
I'm not sure if you are following my point. If a user's project has `redux-thunk` 2.1 installed, installing your lib will also install `redux-thunk` 2.3, simple as that. And you don't seem to rely on something specific from `redux-thunk` 2.3, 2.1 would have done it fine.

**Comment by TrySound** [comment] 2018-06-22 18:41
I get your point. But why just do not upgrade your dependencies?

There are not breaking changes in minor version (usually). This project uses latest versions and may rely on their stuff. Even specifying lower version in package.json will keep in our `node_modules` latest matched versions. We couldn't say if something is broken with real lower version.

**Comment by enapupe** [comment] 2018-06-22 18:54
You are taking my comments as just a single developer that has a single need. I'm talking about library responsibilities and best practices, of course I'll update my deps every time I can.
The point here is that your approach to dependencies leads to fatter bundles simply because you refuse to consider specifying WHAT you need from dependencies - "being up-do-date" is not good reason IMHO.
You understand that you are asking hundreds of developers that will eventually use this library to have matched the same dependencies, simply because...? It should be the other way around - the developer has the deps it has to have and the deps try to fit it, adding as few deps as possible.

I think may be worth referencing #525 as it's more or less on the same topic.

**Comment by enapupe** [comment] 2018-06-22 19:32
@AgentME I agree that yarn could do a LOT better.

But still, I think that it's not about checking all deps against older versions, it's about knowing what you need from a library when you add it. There's usually no need to upgrade/update it unless your library explicitly depends on that update to work;

**Comment by TrySound** [comment] 2018-06-22 20:02
In topic you are talking about patch version which is usually a bug fix. It's probably ok for maintainers to look at used features but it's really annoying to watch which bug was fixed.
> I was bundling react-redux twice because mine was ^5.0.6 and yours ^5.0.7

**Comment by alexreardon** [comment] 2018-06-25 04:57
To clear up any confusion here are my thoughts on the topic:

### General rule

As a general rule, we try to keep some things simple so we can maximise our forward velocity. For example, we are not maintaining old versions of the repo as that would take away the time that we have from moving the project forward.

### Dependencies: keeping on latest

On the topic of dependencies, we have opted for almost always keeping on the latest version of them.

#### Rationale:

- By keeping up with our dependencies we are pushing for the highest level of quality we can. We don't want to be fighting bugs that have already been fixed in later versions of dependencies. 
- Our dependencies are light. We are trying to keep the dependencies for this library as light as possible so if there is duplication - hopefully, it is not a big cost. We are actually removing `redux-thunk` and `reselect` as dependencies in the next version. This only leaves 8 dependencies for the project. The only ones more than 1kb would be `react-redux`, `redux` and `react-motion`.
- Looking through the release notes of each dependency upgrade and discussing whether we need the upgrade to support the library is a time expensive conversation that could be better spent elsewhere. 
- If we did not update our dependencies, when we eventually did that would be a big chunk of work. By keeping on top of them we mitigate risk and break the effort up into smaller chunks.
- People can get correct dependency de-duplication by staying on the latest version of dependencies. This is a good practice that is worth encouraging!

**Comment by alexreardon** [comment] 2018-06-25 23:08
Thanks for challenging us and pushing for greatness

**Closed by alexreardon** 2018-06-25 23:08 UTC
Labels: engineering health

**Comment by enapupe** [comment] 2018-06-25 23:21
Thanks for the complete answer and for not just answering that I should update my deps.

**Comment by waynebloss** [comment] 2018-08-29 01:08
We are forced to use an older version of `react-beautiful-dnd`. So, I searched through the [package.json commit history](https://github.com/atlassian/react-beautiful-dnd/commits/master/package.json) until I found versions that were compatible with the ones being used in our project... (that's v7.1.1 for us).

We have some notes in the project as to why we haven't upgraded to `redux@4` yet:

### Redux

Not upgrading to `redux@4.0.0` because we depend on 
`redux-devtools-extension@2.13.2` for debugging and it doesn't work with 
`redux@4.0.0` yet.

Not upgrading to `redux-persist@5.10.0` because `redux-persist-crosstab` doesn't
work with it yet. There is a workaround, see
[here](https://github.com/rt2zz/redux-persist-crosstab/pull/17) and notes 
[here](https://github.com/rt2zz/redux-persist/issues/569) and elsewhere.

`redux-persist@5.10.0` currently does work with `redux@4`.

**Comment by waynebloss** [comment] 2018-08-29 02:42
To make this library easier to integrate with any project, I think you should declare the most commonly used dependencies as `peerDependencies` with wide [semver ranges](https://docs.npmjs.com/misc/semver#ranges) (e.g. `>=2.0.0 <5.0.0`) or a list of them that are known to work. Then you can put specific versions in your `devDependencies`.

The reason being is that you cannot predict every possible deep dependency linkage that might cause a project to decide to delay upgrading.

NOTE: After investigating our own project that I mentioned previously, I see that `redux-devtools-extension` starting `@2.13.3` is now working with `redux@4`, but `redux-persist-crosstab` still isn't.

**Comment by waynebloss** [comment] 2018-08-29 02:47
I also just noticed how tiny `redux-presist-crosstab` is and that we can probably just in-house it...didn't realize that earlier - however, it'd be much nicer if I could get started now with the latest `react-beautiful-dnd` and do the other thing later...

Anyway, just giving you notes on my thought process as I discover your project here. That experience only happens once... Hope it helps and thanks for all your hard work!

**Comment by krzysiek1507** [comment] 2020-02-27 19:13
Since React is in `peerDependecies`, shouldn't `redux` and `react-redux` be there as well? Please check `react-redux` https://github.com/reduxjs/react-redux/blob/ec38c1bd0026bedca3fd7a8db063f242b0378694/package.json#L38-L41

**Comment by Macil** [comment] 2020-02-27 23:07
React is a peer dependency of react-beautiful-dnd because react-beautiful-dnd has to work with the specific version of React that your application is using. (And redux is a peer dependency of react-redux because react-redux has to work with the specific version of redux your application is using.) However, it doesn't matter to react-beautiful-dnd that your application uses redux or uses the same version as react-beautiful-dnd uses internally. React-beautiful-dnd doesn't integrate at all with your application's version of redux. It just uses its own version of redux internally. It's fine if your application using react-beautiful-dnd doesn't use Redux or uses a different version; it's not fine if your application using react-beautiful-dnd doesn't use React or uses the wrong version.
