### ISSUE TITLE
disableInteractiveElementBlocking doesn't work in firefox

### ISSUE THREAD

**Issue by madebyaaron** [atlassian/react-beautiful-dnd#297] opened 2018-01-27 17:32 UTC
Hi, great library.
I've come across an issue where draggable 'disableInteractiveElementBlocking' prop doesn't work on the latest versions of Firefox (57 & 58)

### Expected behavior
interactive elements within a draggable item should begin the drag interaction (in my case this is a disabled textarea)

### Actual behavior
Draggable item isn't draggable when clicking on textarea element. The draggable item is draggable when i click anywhere else within the draggable item.

### Steps to reproduce
Create a draggable element, Add in a textarea (or any interactive) element, and attempt to pick up the draggable item via the textarea.

### Browser version

I've only discovered this bug in:
Firefox (57 & 58)

Chrome and safari are fine. (I shall update this as i continue testing)

**Comment by alexreardon** [comment] 2018-01-30 06:29
Give that I cannot reproduce this and there is no new information i'll close this for now. Please re open if new information comes to light! An independent example would be great

**Closed by alexreardon** 2018-01-30 06:29 UTC
Labels: more information required
