### ISSUE TITLE
Containing element receives mouse click after dragging

### ISSUE THREAD

**Issue by lukebarnard1** [atlassian/react-beautiful-dnd#273] opened 2018-01-16 10:42 UTC
## Bug or feature request?
Bug

### Expected behavior
A mouse click event is not emitted on the parent element of the draggables after dragging and dropping.

### Actual behavior
A mouse click event *is* emitted on the parent element of the draggables after dragging and dropping.

### Browser version
Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Demo

See logs of the following demo after dragging and dropping:
https://www.webpackbin.com/bins/-L2yYhx5eZi1MJnlU-79

**Comment by alexreardon** [comment] 2018-01-16 23:05
Interesting. We are blocking the event:

```js
const onClick = (event: MouseEvent): void => {
    if (!state.preventClick) {
      return;
    }

    // preventing click

    // only want to prevent the first click
    setState({
      preventClick: false,
    });

    // this will stop propagation and prevent default
    stopEvent(event);
  };
```

**Comment by alexreardon** [comment] 2018-01-16 23:52
This is very strange. I can see the issue in the basic example, but i cannot reproduce it in our examples. It looks like the draggable wrapper div is the target of the event which seems strange. I'll keep looking

**Comment by alexreardon** [comment] 2018-01-16 23:52
Webpack bin seems to be down so i'll take a look at this later

**Comment by alexreardon** [comment] 2018-01-17 01:14
Okay, I can see what the issue is:

When we are dragging we add `pointer-events: none`. To the drag handles. This means that when the user lifts there mouse a click event may occur but its `event.target` will be the `div` above the drag handle. 

This is not the case for anchor tags which still get the click event 🙃

Some suggestions:

- remove: `pointer-events: none` off the drag handle. (You could make this patch yourself) However, doing this will prevent the standard scroll actions while a drag is occurring.
- Add a onClick handler to the parent of the drag handle and call event.stopPropagation() to prevent the click from bubbling up. 

Sadly I do not think we can remove `pointer-events: none` at a library level as it is the only way to scroll while dragging until #27 lands. So I think the second option is your best option for now

**Comment by alexreardon** [comment] 2018-01-17 01:15
Given that there is no further action to be taken at this time i'll close this. If people think that this problem should be solve more thoroughly we could revisit it. It will be a slightly different conversation after #27 lands.

**Comment by alexreardon** [comment] 2018-01-17 08:17
This makes me sad. I am going to see if we can do better

**Comment by alexreardon** [comment] 2018-01-17 21:09
The trouble is even when if we remove `pointer-events: none` from the drag handles directly after a mouse up it does not change the click behaviour. It needs to not be there when the click actually occurred. Given that we currently need `pointer-events: none` to enable scrolling we cannot change this. Also, pointer-events: none adds some awesome performance. We would need to investigate the perf impact of removing it.

For now here is the best workaround:

```diff
+<div onClick={provided.dragHandleProps.onClick}>
  <div
    ref={provided.innerRef}
    {...provided.draggableProps}
    {...provided.dragHandleProps}
    style={getItemStyle(
      snapshot.isDragging,
      provided.draggableProps.style
    )}
  >
    {item.content}
  </div>
  {provided.placeholder}
</div>
```

By binding the drag handle onClick function to the parent you get the correct click blocking behaviour. This will allow actual clicks to go through, while blocking clicks after a drag (which is what already occurs on an anchor)

**Comment by lukebarnard1** [comment] 2018-01-18 18:11
@alexreardon thanks for looking into this - your response was very speedy! 😄 

The workaround seems fine to me.

**Comment by alexreardon** [comment] 2018-01-18 23:37
The best fix would require us to add an event handler to the parent. This could done without the consumers needing to bind it...
🤔

**Closed** 2018-02-28 03:28 UTC
Labels: idea

**Comment by jeduardo824** [comment] 2020-05-12 01:07
Hey @alexreardon, is this working? I'm with a similar error on IE 11, and I tried with what you proposed but no success.

**Comment by davidhan527** [comment] 2020-08-09 15:53
Hi @alexreardon , I see that future versions of the project removed the `provided.dragHandleProps.onClick` function and so your workaround in https://github.com/atlassian/react-beautiful-dnd/issues/273#issuecomment-358446062 no longer works. I'm on the most recent version of the library. Any ideas on a different workaround now that `provided.dragHandleProps.onClick` was removed?

**Comment by mrmowji** [comment] 2021-03-27 10:07
Have you tried `event.defaultPrevented` on the parent's `onClick`?

**Comment by glenames** [comment] 2021-04-20 19:32
A little helper while awaiting anything 'official' the onClick event of the parent has property defaultPrevented set to true after a drag event on its child. So in your parent onClick event handler you can do something like:

if (!e.defaultPrevented) doSomething...
