### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by danieldelcore** [atlassian/react-beautiful-dnd#1053] opened 2019-01-14 02:42 UTC
## Bug or feature request?

Bug

## Bug
After leaving the [large data set example](https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=large%20data%20set&full=0&addons=1&stories=1&panelRight=0) open in a tab for an extended period of time, I noticed the drag and drop experience slowed down and became quite jumpy. Eventually my chrome tab crashed. 

I suspect that there could be a memory leak somewhere in either the example or the library.

I ran the profiler on the example and dragged elements around. I noticed that event handlers were being attached and not dereferenced. This accumulates over time and starts to slow down the experience. (Profiler output below)

<img width="1391" alt="screen shot 2019-01-14 at 11 53 03 am" src="https://user-images.githubusercontent.com/3030010/51094529-ff5f9980-1801-11e9-8e58-6ccfb4e81101.png">

For some context, the peaks indicate when elements were dragged around, while the flat areas was time spent idling. You can see that the event listeners increase steadily, to a total of 1134 instances, and were never removed after the drag event finished. There also seems to be some correlation between the nodes appended to the page while dragging and the event listeners that are attached to those nodes. 

Please let me know if there's anything i can do to help. 

### What version of `React` are you using?

react: ^16.4.0

### What version of `react-beautiful-dnd` are you running?

v10.0.3

### What browser are you using?

Chrome Latest

### Potential Duplicates
https://github.com/atlassian/react-beautiful-dnd/issues/233

**Comment by alexreardon** [comment] 2019-01-22 23:06
I have added a help wanted label to this one as i think somebody could look into this without having much understanding of how the library hangs together

**Comment by danieldelcore** [comment] 2019-01-22 23:42
No worries, i'll have a look sometime this week 😄

**Comment by niwsa** [comment] 2019-02-21 19:25
I guess all the event listeners are being cleaned up with unbindWindowEvents
  `const unbindWindowEvents = () => {
    const win: HTMLElement = getWindow();
    unbindEvents(win, windowBindings, { capture: true });
  }; `
Except for 'load' and 'error' event listener that were on each draggable image if I remember correctly.Suspect these two listeners inside each draggable adds up to the count of unremoved listeners.Could'nt find the source where they are getting added.

**Comment by alexreardon** [comment] 2019-02-21 21:45
How did you go @danieldelcore ?

**Comment by danieldelcore** [comment] 2019-02-21 23:30
Hey @niwsa @alexreardon, 

Sorry i haven't had a chance to have a look that this yet 😭
But the above is probably a great place to start!

**Comment by alexreardon** [comment] 2019-02-22 03:51
We don't load any load and error listeners 😕

**Comment by niwsa** [comment] 2019-02-22 16:22
![image](https://user-images.githubusercontent.com/3107922/53255498-bbf32780-36eb-11e9-944a-32ad66700440.png)
I 'm seeing the above two listeners for each avatar image

**Comment by niwsa** [comment] 2019-02-24 17:47
From what I see the event handlers are added by react just checked a couple of react web apps and you can see that  :)

**Comment by alexreardon** [comment] 2019-02-24 22:05
So is this a react issue? 😲

**Comment by jfrej** [comment] 2019-03-27 16:28
This _might_ be related: I recently found an issue with growing number of DOM Nodes when switching between a page with `react-beautiful-dnd` and others.
It looks like `react-beautiful-dnd` never properly releases any DOM Nodes and they're kept in memory forever.

We're using `react-router` in our app, but here's a simple reproduction using state to toggle dnd components: https://codesandbox.io/s/r7pjow02yo

Here's what the performance graph looks like for the reproduction after a minute of toggling:

![image](https://user-images.githubusercontent.com/11192156/55092713-ed745f80-50aa-11e9-96e2-094eed5c1644.png)

Notice the growing number of Nodes (green line) and JS Heap (blue). They never go down, even after forcing garbage collection or after waiting for a long time.

Please let me know if I should log this as a separate issue.

**Comment by readikus** [comment] 2019-06-07 10:11
This may be partially related, or a separate issue.

I've been doing some investigation work into memory leaks on one of our apps, and some tests today found issues with this module. From the heap traces, there seems to be issue `lastPropsRef` containing references to the DOM nodes being retained in your redux store. This was keeping the nodes alive (we used it in a popup). So each time that popup was rendering, it was never releasing.

**Comment by alexreardon** [comment] 2019-07-22 03:40
I think this is fixed in 12.0. Can you please check @danieldelcore 

See `virtual` branch

**Comment by alexreardon** [comment] 2019-11-05 02:29
We are closing this issue due to inactivity. If you would like to continue the conversation feel free to reply to this issue and we can reopen it if needed.

**Closed by alexreardon** 2019-11-05 02:29 UTC
Labels: help wanted 👋, improvement ⭐️
