### ISSUE TITLE
Uncaught TypeError: $.memo is not a function at react-beautiful-dnd.cjs.js

### ISSUE THREAD

**Issue by gitJoe42** [atlassian/react-beautiful-dnd#1416] opened 2019-07-18 13:35 UTC
### Expected behavior

App starts without an error

### Actual behavior

Crashes in the live version, but not locally

### Steps to reproduce

Unfortunately I cannot reproduce this behavior locally. It only happens live

### What version of `React` are you using?

16.3.2

### What version of `react-beautiful-dnd` are you running?

11.0.4

### What browser are you using?

Chrome Version 75.0.3770.142

### Demo

Unfortunately I cannot provide a demo for this issue, because I cannot reproduce the error locally. The error only arises in the live version of our app.

Our app crashes, when we use react beautiful dnd with these two errors in the browser console:

```3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:15 Uncaught TypeError: $.memo is not a function
    at react-beautiful-dnd.cjs.js (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:15)
    at a (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at e (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at TabOfferMain.jsx (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133)
    at a (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at e (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at TabOffer.jsx (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133)
    at a (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at e (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13)
    at SystemFormTabs.jsx (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133)
react-beautiful-dnd.cjs.js @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:15
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
TabOfferMain.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
TabOffer.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
SystemFormTabs.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
SystemForm.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
EditSystemData.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
routes.jsx @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
main.js @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
a @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
e @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:13
(anonymous) @ 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:133
3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:91



Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
    at 3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:91
    at a (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:1)
    at HTMLDocument.u (3489332cbf3c95f9db0dd9714545c68ba4361e25.js?meteor_js_resource=true:1)
```

I know, that it is difficult to get a solution without further information. But that's my problem. Does anyone has an idea how to approach this issue?

**Comment by alexreardon** [comment] 2019-07-21 22:02
> The error only arises in the live version of our app.

Ouch!

It looks like the error stack you provided is calling out a separate error:

```
Cannot read property 'ServiceConfiguration' of undefined
```

**Comment by Pixelatex** [comment] 2019-07-31 07:32
Same issue, if you remove your node_modules and reinstall them. It crashes. I think something changed in the package

**Comment by Pixelatex** [comment] 2019-07-31 07:34
my package is set to "    "react-beautiful-dnd": "latest"," somehow.. which explains my issue I guess. I think gitjoe42 might have a similar issue.

**Comment by TrySound** [comment] 2019-07-31 07:38
Yep, required react version is 16.8.5
https://github.com/atlassian/react-beautiful-dnd/blob/master/package.json#L137

**Comment by Pixelatex** [comment] 2019-07-31 08:00
can confirm, just upgraded my react versions and set it to version 11 instead latest to prevent this from occuring again.

**Comment by gitJoe42** [comment] 2019-07-31 09:54
Thanks for your help. I can confirm that setting react version in package.json to ^16.8.6 prevents this error occurring. Our app loads, but on some actions we get a new error and the app crashes :(

18bfae6……js_resource=true:15 Invariant Violation: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Pixelatex** [comment] 2019-07-31 09:56
My guess is that the library is using hooks somewhere. You can try to lower the version of dnd to a pre-hook version?

**Comment by kevinjihwanlee** [comment] 2019-07-31 20:53
@Pixelatex According to the [changelog](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v11.0.0) v11 switched over the source to React ^16.8.5 to make use of hooks, so your guess is right

**Comment by alexreardon** [comment] 2019-08-02 06:13
It looks like this issue is caused by using a react version that does not satisfy our react peer dependency. I will close this for now

**Closed by alexreardon** 2019-08-02 06:13 UTC
Labels: more information required, question ❓
