### ISSUE TITLE
More information on autoscrolling?

### ISSUE THREAD

**Issue by AndrewMorsillo** [atlassian/react-beautiful-dnd#354] opened 2018-02-27 22:40 UTC
Bug report / information request.

First of all, v5.0.0 and this project are absolutely great! Thanks so much for publishing this great library.

I am having an issue with autoscrolling. It is working fine on my desktop layout but not working on my mobile layout (in chrome on android) which isn't significantly different. I am not sure how to debug this issue as the docs say very little about autoscrolling. Perhaps it would be possible to let users specify the DOM element to use for scrolling?

**Comment by yogaboll** [comment] 2018-03-01 15:21
Autoscrolling doesn't work on mobile for me. It's broken on [the board example](https://react-beautiful-dnd.netlify.com/iframe.html?selectedKind=board&selectedStory=simple) on both Chrome on 
android and Chrome on desktop in mobile device mode. 
![people tell this gif is amazing](https://media.giphy.com/media/6ob4zAvH5rP1Ykdfmr/giphy.gif)

**Comment by alexreardon** [comment] 2018-04-14 03:04
Is this still occurring? I am unable to reproduce it...

**Comment by alexreardon** [comment] 2018-04-14 03:04
Closing for now unless more information comes to light

**Closed by alexreardon** 2018-04-14 03:04 UTC
Labels: more information required
