### ISSUE TITLE
auto scrolling fail after scroll to the bottom

### ISSUE THREAD

**Issue by oahehc** [atlassian/react-beautiful-dnd#539] opened 2018-06-04 02:44 UTC
## Bug or feature request?
Bug

### Expected behavior
auto scroll up when drag component to top of the container

### Actual behavior
unable to auto scrolling after scroll to the end of container

### Steps to reproduce
apply [vertical list example](https://codesandbox.io/s/k260nyxq9v ) and wrapper by a div with fix height/width

### Browser version
chrome Version 66.0.3359.181 (Official Build) (64-bit)

### Demo
https://codesandbox.io/s/v06zxpxnp5
![jun-04-2018 10-20-11](https://user-images.githubusercontent.com/13633490/40895364-996d83f6-67e1-11e8-9956-95b305c34812.gif)

thanks for the help~

**Comment by alexreardon** [comment] 2018-06-04 09:07
That looks bad, but i am unable to reproduce on my machine!

🤕

**Comment by oahehc** [comment] 2018-06-04 09:17
Hi @alexreardon 
Is the [Demo](https://codesandbox.io/s/v06zxpxnp5) also work on your machine?
This only happen when I drag and auto scrolling to bottom, then it won't be able to scroll back.
And I only wrap the original example with this
```
<div style={{ height: "150px", width: "270px", overflow: "auto" }}>
   ...
</div>
```

**Comment by alexreardon** [comment] 2018-06-06 11:42
I have tested https://v06zxpxnp5.codesandbox.io/ on chrome, FF, and safari and i am not seeing the behaviour that you have recorded... 

I am not sure what else i can do at this stage. I will close this issue as there is nothing for us to action. If any new information comes to light I am happy to reopen it

**Closed by alexreardon** 2018-06-06 11:42 UTC
Labels: more information required

**Comment by oahehc** [comment] 2018-06-07 00:09
@alexreardon 
many thanks for the help, 
I will try again and provide more information if this issue still exist.

**Comment by oahehc** [comment] 2018-06-08 07:32
Hi @alexreardon 
I think this only happen when using mac with mouse, 
because mac will handle scrollbar differently with and without mouse.

![jun-08-2018 15-25-06](https://user-images.githubusercontent.com/13633490/41144896-ef8150f4-6b30-11e8-900b-9b7483ba3d0e.gif)

**Comment by dimitarnestorov** [comment] 2018-06-08 10:50
This is the problem:
![image](https://user-images.githubusercontent.com/8790386/41154192-08ee1612-6b22-11e8-8bc3-a4936376b6c9.png)

It usually is the first option, and when you put a mouse that isn't Apple branded, `automatically` == `always`.

There is no space for the content and the scrollbar causing a horizontal scrollbar. Easiest fix: remove the horizontal scrollbar by setting `overflow` to be `hidden auto` as shown here: https://codesandbox.io/s/wyvpvxrl1k
What I recommend is to use CSS to cause the scrollbar to show up on hover by toggling `overflow-y` if you NEED a constant width for the list.

**Comment by oahehc** [comment] 2018-06-11 09:05
@dimitarnestorov 
thanks, "hover by toggling overflow-y" did solve this issue.
also update the [Demo](https://codesandbox.io/s/v06zxpxnp5) for reference.

**Comment by amjedomar** [comment] 2021-07-25 07:23
I was facing the same problem however when I add the `{provided.placeholder}` React Node as a child of Droppable the problem solved.
