### ISSUE TITLE
core-js 2 as dependency

### ISSUE THREAD

**Issue by Bielik20** [atlassian/react-beautiful-dnd#1629] opened 2019-11-24 09:06 UTC
### Expected behavior

Polyfills should not be included in library, there should be an instruction what is expected to be included in actual app to support given browser.

### Actual behavior

App expects core-js 2 as a dependency. That breaks apps based on core-js 3.

### Steps to reproduce

If your react app polyfills look somewhat like that: 
```
import 'core-js/stable';

import 'regenerator-runtime/runtime';
```
Then compilation will fail.

### Suggested solution?

Remove polyfills from bundle.

### What version of `React` are you using?

`16.10.2`

### What version of `react-beautiful-dnd` are you running?

`11.0.3`

**Comment by carlosagsmendes** [comment] 2019-11-25 20:11
I'm experiencing the same issue using webpack with core-js 3

**Comment by carlosagsmendes** [comment] 2019-11-26 11:21
@Bielik20 would you mind sharing your babel settings? I'm trying to reproduce on a webpack 4 installation from scratch

**Comment by Bielik20** [comment] 2019-11-26 15:38
@carlosagsmendes I am using [nrwl](https://github.com/nrwl/nx) to manage my monorepo. It is default config from there.

**Comment by alexreardon** [comment] 2019-11-26 23:50
I'm not sure what the best approach for us should be. Any thoughts @TrySound @theKashey

**Comment by theKashey** [comment] 2019-11-27 00:36
There are two moment - safety and the ease of use. `core-js` 2/3 is a really big problem and the number affected users would grow, so you have to remove it.
However, it should be a breaking change, or __existing installations would break__.

In short:
- don't include polyfills. As well as ponyfills*
- test and document which ones are required for you. You can use `usage-plugin` in debug more to get a list of polyfills which are _potentially_ required by this library. Keep in mind - that list would be different for `core-js2` and `core-js3`
- after knowing which polyfills are really required you might use ponyfills for some of them (like using `lodash` instead of Array.methods)
- no further talks before the list of polyfills is known (I'll provide it in a hour)

**Comment by alexreardon** [comment] 2019-11-27 03:41
Ideally, we are not pollyfilling anything. That was my understanding is that we are only using ponyfills

**Comment by theKashey** [comment] 2019-11-27 04:05
From the code - no, you are not. At least it's not documented - https://github.com/atlassian/react-beautiful-dnd/search?q=runtime-corejs2&unscoped_q=runtime-corejs2 and the only expected polyfills are Number.isInteger and Object.values, which could be ponyfilled... but you can't import thst ponyfill from some specific core-js version(though `runtime-corejs2`).

**Comment by theKashey** [comment] 2019-11-27 04:54
| File | Required |
| ------------- |:-------------:|
| invariant.js  | es.object.to-string,es.regexp.to-string |
| dev-warning.js | es.string.trim, es.string.replace |
| native-with-fallback.js  | es.object.values,es.array.find-index,es.array.find,es.array.slice,es.object.to-string,es.array.iterator,web.dom-collections.iterator  |
| index.js       |es.weak-map,es.object.to-string,es.string.iterator,es.array.iterator,web.dom-collections.iterator,es.object.get-own-property-descriptor     |

**Comment by TrySound** [comment] 2019-11-27 09:21
Users should provide own polyfills. Though the library may omit usage of a set of functions and implement their loose versions for specific need. I would prefer to drop core-js. rbd is the only lib in my app with core-js in dependencies. And one of a few last commonjs modules.

**Comment by theKashey** [comment] 2019-11-27 21:27
Yep. _"omit usage of a set of functions"_ is one of the reasons why I tend not to use `Object.values`

**Comment by alexreardon** [comment] 2020-01-09 06:19
@TrySound happy for a PR to make this happen! It was my understanding that we did not polyfill anything (only ponyfills). If we are polyfilling that is bad news.

**Comment by danieldelcore** [comment] 2021-03-23 04:22
Looks like this has already been resolved by @TrySound (Thanks)! 

Will close for now but please feel free to reopen if this is still an issue for you!

**Closed by danieldelcore** 2021-03-23 04:22 UTC
Labels: good first issue ❤️, help wanted 👋, idea 🤔
