### ISSUE TITLE
Capture current x-axis scroll position on board

### ISSUE THREAD

**Issue by Ajaay** [atlassian/react-beautiful-dnd#1198] opened 2019-03-23 11:51 UTC
Question - What is the easiest way to capture current horizontal scroll position on a board?

My draggables in each list open a modal and when the modal is closed, the board scroll position is reset to the beginning. I would like to maintain my x-axis scroll position when closing the modal.

Thanks!

**Comment by alexreardon** [comment] 2019-03-25 05:32
Hi there!

Thanks for raising this issue. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, we will not be able to action this one

Cheers!

**Comment by alexreardon** [comment] 2019-03-25 05:33
A loss of scroll position seems strange. React is usually quite good at maintaining it. What you are seeing also seems to be outside of the scope of responsibility of this library.

I will close this issue for now for that reason. But feel free to respond with a reproducible sandbox and I can try to take a look

**Closed by alexreardon** 2019-03-25 05:33 UTC
Labels: more information required
