### ISSUE TITLE
The Course is off line ?

### ISSUE THREAD

**Issue by shpsyte** [atlassian/react-beautiful-dnd#2088] opened 2021-02-12 01:15 UTC

**Comment by danieldelcore** [comment] 2021-02-12 01:18
Hi there, looks like the course is still online and available here: https://egghead.io/courses/beautiful-and-accessible-drag-and-drop-with-react-beautiful-dnd

Is there a broken link somewhere that needs updating?

**Comment by danieldelcore** [comment] 2021-02-12 01:22
Duplicate of  #2089

**Closed by danieldelcore** 2021-02-12 01:22 UTC
Labels: docs 📖
