### ISSUE TITLE
Force press clicking messes with Dragging on Safari

### ISSUE THREAD

**Issue by v0lkan** [atlassian/react-beautiful-dnd#62] opened 2017-08-28 21:48 UTC
## Bug or feature request?
Bug

### Expected behaviour

When releasing her finger from the trackpad, the card should remain to the list; it should not remain sticked to the cursor

### Actual behaviour

See video https://www.youtube.com/watch?v=-gWQ9hkjUj8

The radar effect happens when the user releases the card.
Even though the user releases the card, she can still move things around.

This bug manifests itself on all the example pages.

### Steps to reproduce

See https://www.youtube.com/watch?v=-gWQ9hkjUj8

You probably need a magic trackpad instead of a mouse.
Isssue manifests itself in the recent Mac OS, at the very least.

I suspect, but I haven’t time to dig in, that it might be related to “force touch”.

### Demo

Here is a video with pointer events recorded, to help you:

 https://www.youtube.com/watch?v=-gWQ9hkjUj8

**Comment by alexreardon** [comment] 2017-08-29 00:46
Thanks for the video @v0lkan! This does not look good. I will try get get access to a touch pad to see if I can reproduce this.

**Comment by v0lkan** [comment] 2017-08-29 01:51
Happy to help @alexreardon 

In case you cannot repro, I can come to Atlassian Mtn. View office, and show it myself :)

Atlassian is literally 5 minutes driving distance from me :D

Cheers,

V.

**Comment by alexreardon** [comment] 2017-08-29 01:54
I am in the Sydney office - and all good. I found one :)

**Comment by v0lkan** [comment] 2017-08-29 01:55
:) — Sydney is a bit far away, I guess.

**Comment by alexreardon** [comment] 2017-08-29 23:58
@v0lkan can you please post a screenshot of your trackpad settings?

**Comment by alexreardon** [comment] 2017-08-30 00:58
I have been playing with a variety of settings and I cannot seem to reproduce this behaviour

**Comment by v0lkan** [comment] 2017-08-30 03:33
> I have been playing with a variety of settings and I cannot seem to reproduce this behaviour

I am using a magic trackpad (the new one) on Mac OS Sierra.

My trackpad settings are extremely sensitive (not everyone uses it like that) — see attached image.

![screen shot 2017-08-29 at 8 32 16 pm](https://user-images.githubusercontent.com/1041224/29854201-445ee54e-8cf9-11e7-816a-d63504007231.png)

So my guesstimate is, I might be clicking something between a force touch and a regular touch.

**Comment by v0lkan** [comment] 2017-08-30 03:38
@alexreardon here is a different variation » https://youtu.be/4MGnLO9lxyc

**Comment by v0lkan** [comment] 2017-08-30 03:39
Using Safari, btw; not sure it’s the same for Chrome.

**Comment by alexreardon** [comment] 2017-08-30 03:45
I have tried in safari with all of your settings and I am still unable to reproduce. Hmm..

**Comment by v0lkan** [comment] 2017-08-30 03:47
:) Unless I’m on an alternate universe, I can reproduce it %100 of the time.

I will try with a brand new Mac OS probably/hopefully within a few days.

**Comment by alexreardon** [comment] 2017-08-30 04:13
When you hover over a link a quick link pops up - how do you activate that?

**Comment by v0lkan** [comment] 2017-08-30 04:20
@alexreardon it is called “force touch” or something like that; you press deeper. — Only on new trackpads and new macs.

ref: https://support.apple.com/en-us/HT204352

See the “force click and haptic feedback” option on the settings I shared above.

**Comment by v0lkan** [comment] 2017-08-30 04:32
There is also an “in between” state. Hard to describe but, like a “half click”.

If you check this video https://www.youtube.com/watch?v=4mQ8g9Y9Q_U you can see that the size of the popover changes. — The deeper I press, the bigger the popover is. — If I press deep enough, then a permanent popover is displayed.

Certain apps (on ipad and iPhone — not sure if on Macs too) also utilize this in-between state for other interactions.

I’m not sure what kind of quirky sequence of mouse events (or touch events) these force gestures trigger; but I suspect that it is what makes things out of order.

That said, I haven’t checked the source or debugged it to clarify things further.

Hope that helps.

**Comment by alexreardon** [comment] 2017-08-30 04:38
ah okay - i do not have the latest trackpad or mac - so that would be why i cannot reproduce it. I will try to track down a later model

**Comment by v0lkan** [comment] 2017-08-30 04:41
^ will try to verify w/o haptic settings to see if it reproduces.

If your hypothesis is true, then it should not repro w/o haptic feedback enabled.

(thinking about how this discussion would look like five years into the future; UX changes a lot!)

**Comment by v0lkan** [comment] 2017-08-30 04:45
confirmed! with force touch **disabled**, everything works like butter on a pancake!

That should reduce the scope a bit.

**Comment by alexreardon** [comment] 2017-08-30 04:48
Getting closer! I will try to wrangle a appropriate piece of hardware so i can move forward

**Comment by alexreardon** [comment] 2017-08-30 04:59
I updated the description in light of our findings

**Comment by alexreardon** [comment] 2017-08-30 23:45
I have put in a request to get the appropriate hardware. I'll keep you updated

**Comment by alexreardon** [comment] 2017-08-31 05:37
I have a fix. It almost broke me. So sad that safari decided to do its own thing
https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/SafariJSProgTopics/RespondingtoForceTouchEventsfromJavaScript.html

I will write some tests and push it up

**Comment by alexreardon** [comment] 2017-08-31 23:37
Unfortunately this will not be fixed if you are using `react-beautiful-dnd` inside of a iframe (such as [our storybook examples](https://react-beautiful-dnd.netlify.com)). This is because of a [bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=176195) where the mouse force touch events are not published inside of an iframe. 

Given that this is a browser issue there is no work around for it at this time. So if you are creating draggable anchors inside of an iframe and the user is using safari and has a force touch device - things will not be good for them. My hands are tied until the bug is fixed within Safari.

**Closed** 2017-08-31 23:49 UTC
Labels: bug

**Comment by v0lkan** [comment] 2017-09-01 02:08
`webkitmouseforcechanged` => Agree that it’s kind of annoying to do vendor-specific code forks because a specific vendor goes out of whack. 

It reminds me of the days we maintained two separate code bases for IE5 and NN4. — I would hate to see those days back :)

That said, the patch is nicely-abstracted; anyone who does not support the force touch change event won’t be impacted at all. — 👏 for that.

**Comment by alexreardon** [comment] 2017-09-01 06:23
You're welcome @v0lkan

**Comment by alexreardon** [comment] 2017-09-20 20:48
I have another idea for those who need to want to have draggable anchors inside an iframe:

Add a window event listener within your application (the part that is inside the iframe). Add an event listener for `webkitmouseforcechanged`. Within that listener always call `event.preventDefault`. That will disable force press previews altogether (which I think is fine) and dragging will work as expected.
