### ISSUE TITLE
How to limit the drag area to the DragDropContext

### ISSUE THREAD

**Issue by SandMoshi** [atlassian/react-beautiful-dnd#846] opened 2018-10-05 18:00 UTC
There is a bug, where if one of my draggables is 120px tall and I try to drag it to a list that ends less than 120px from the bottom of the page it can cause the droppables and draggables to flicker as the droppable column changes heights back and forth. I believe it's because this causes the height of the droppable to flicker which causes the scroll to flicker which also causes bugs in how flexbox displays the other draggables nearby. 

This usually happens when the center (based on height) of the draggable sits exactly ontop of the bottom border of the droppable. 

I am thinking, if I can prevent the draggable from being dragged below the bottom of the DragDropContext then it will prevent this bug from occurring. Is this possible to accomplish?

**Comment by alexreardon** [comment] 2018-10-07 07:55
I think this is a duplicate of #764.

It should be fixed in `next`

Can you please try using the following and see if your issue remains?

`react-beautiful-dnd-next@10.0.0-alpha.2`

**Comment by SandMoshi** [comment] 2018-10-08 23:55
I can verify that it definitely is the same problem as the one you linked.

However I haven't been able to test your new version yet. Will let you know
when I do.

**Comment by alexreardon** [comment] 2018-11-21 05:11
We are closing this issue due to inactivity. If you would like to continue the conversation feel free to reply to this issue and we can reopen it if needed.

**Closed by alexreardon** 2018-11-21 05:11 UTC
Labels: more information required
