### ISSUE TITLE
react-beautiful-dnd and semantic-ui-css compatibility issue

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [atlassian/react-beautiful-dnd#904] opened 2018-11-10 12:25 UTC
## Bug or feature request?

Bug

### Expected behavior
I expect to be able to drag an item from the top of the list and drop it at the bottom of it when using semantic-ui-css.
### Actual behavior
Cant drop the first item for example at the bottom of the list unless removing `import "semantic-ui-css/semantic.min.css";` or make the body height `auto` which is set by semantic-ui-css to `100%` and will affect the Semantic UI components and the entire website.
### Steps to reproduce
Drag the first list item and drop it at the bottom of the list.

### What version of `React` are you using?
My local React version is 16.6.1 and the demo version is 16.0.1

### What version of `react-beautiful-dnd` are you running?
9.0.2

### What browser are you using?
Google Chrome

### Demo
https://codesandbox.io/s/5mo465r1l

**Comment by mwood23** [comment] 2018-11-14 15:03
@MohammedAl-Mahdawi I've been using this with Semantic and agree that their CSS does mess with react-beautiful-dnd some. A work around I've been using is setting scroll on the list container. It throws a warning in the console, but I'm not sure why because there's only one scroll container that I can see. I've been using to drag between lists and rearrange lists with no problems at all.

Updated demo: https://codesandbox.io/s/5ylov12v3l

**Comment by MohammedAl-Mahdawi** [comment] 2018-11-14 17:33
@mwood23 Thanks for your help, however, your workaround didn't work for me because I don't want to add a scrollbar to the list.

**Comment by alexreardon** [comment] 2018-11-14 21:30
The issue is caused by `overflow-x: hidden` on the body. `react-beautiful-dnd` is treating this as a scroll container, even though it is not one. 

So for your use case you can just remove that style. However, I also think we should update `react-beautiful-dnd` to not consider elements with `overflow: hidden` as scroll containers

**Comment by alexreardon** [comment] 2018-11-14 23:35
Also relevant: https://www.brunildo.org/test/Overflowxy2.html

**Comment by alexreardon** [comment] 2018-11-14 23:37
I am not sure how we are going to distinguish between elements that only have overflow-*: hidden with an overflow-* auto on the other axis...

It is possible to have a scroll container that is overflow-x: hidden and overflow-y: auto that is a scroll container

It is also possible to have a scroll container that is overflow-x: hidden and overflow-y: auto that is *NOT* a scroll container

**Comment by alexreardon** [comment] 2018-11-15 00:13
I am a bit stuck as I cannot figure out a way to distinguish between the two cases. For now just remove the `overflow-x` from the body `body { overflow-x: visible; }` while we try to find a more generic way...

**Comment by MohammedAl-Mahdawi** [comment] 2018-11-15 05:05
Hi @alexreardon Thanks a lot for your help, I used `body { overflow-x: visible; }` hopefully it won't break anything in the project and I'll wait for your generic solution.

**Comment by alexreardon** [comment] 2018-11-15 06:33
I am creating a more generic solution

**Comment by alexreardon** [comment] 2018-11-15 10:04
Here is a new guide I have been writing: https://github.com/atlassian/react-beautiful-dnd/blob/61a3e210d47987e377cc4bbb1a69316311b6067f/docs/guides/how-we-detect-scroll-containers.md

**Comment by MohammedAl-Mahdawi** [comment] 2018-11-15 16:43
@alexreardon using `body { overflow-x: visible; }` cause a horizontal scroll bar to appear so I removed it, also using `body { overflow-y: scroll; }` didn't solve the issue, I'll wait for the pull request to be merged then I'll test again.

**Comment by alexreardon** [comment] 2018-11-19 21:55
This will be fixed by #929

**Closed** 2018-11-20 00:04 UTC
Labels: improvement ⭐️, investigating 🕵️‍♂️
