### ISSUE TITLE
Visual bug on drop

### ISSUE THREAD

**Issue by iago-mendes** [atlassian/react-beautiful-dnd#2086] opened 2021-02-09 12:57 UTC
### Expected behavior

After dropping a draggable element, it should behave like in the official [simple board example](https://react-beautiful-dnd.netlify.app/?path=/story/board--simple).

### Actual behavior

After dropping a draggable element, there is a visual bug as shown in the following GIF.
![](https://media.giphy.com/media/qplSC9LqPNjEJYv9BY/giphy.gif)

### Steps to reproduce

The code for this page can be seen [here](https://github.com/iago-mendes/cinephix/blob/main/src/pages/user/tvshows/index.tsx).

### Suggested solution?

I don't know how to solve this.

### What version of `React` are you using?

17.0.1
OBS.: I'm using Next.js (10.0.4)

### What version of `react-beautiful-dnd` are you running?

^13.0.0

### What browser are you using?

I recorded the GIF on Vivaldi, but I have also tested this in Chromium and Firefox, which had the same visual bug.

### Demo

This bug is happening in a website in production, which can be used as a Demo. It can be accessed on [cinephix.com](https://cinephix.com/user/tvshows), but it is required to sign in with a Google account and add some elements to your account.

**Comment by danieldelcore** [comment] 2021-03-23 00:04
Hi @iago-mendes , can you please provide a reproduction in [codesandbox](https://codesandbox.io/s/new)? It would be really helpful for me to help diagnose the problem. 🙏

**Comment by danieldelcore** [comment] 2021-03-23 05:28
Also, it might be that you have additional transitions & animations on your draggable items. if so, please try removing them 👍

**Comment by VArsenyan** [comment] 2021-04-05 08:33
Have same issue too, any fix ideas?

**Comment by iago-mendes** [comment] 2021-04-14 01:46
@danieldelcore, here's the reproduction you asked for: [rbd-issue-2086-ixi6v](https://codesandbox.io/s/rbd-issue-2086-ixi6v).

Since I haven't used CodeSandbox before, I have probably done something wrong. For some reason, sometimes the page built when you enter the project doesn't include the styles. The work around I used for that is described below:

1. Create a new terminal
2. Run `yarn dev -p 2001` (2001 is just a random port different from 3000)
3. Then, CodeSandbox will probably ask if you want to open the new port in the browser, so click on 'yes'

As you suggested, I have tried removing other transitions and animations on my draggable items (not reproduced in the project above), but it didn't solve the problem.

**Comment by VArsenyan** [comment] 2021-04-15 11:13
Upd: any fixes?

**Comment by danieldelcore** [comment] 2021-04-16 01:06
Hi there 👋  thanks for providing a reproduction. I've just had a look now. 

Looks like your issue is with your CSS.

Some things I noticed:

1. We're setting `transition: 0.25s;`  on the `.tvshow` class. This can cause various issues with performance and rendering. It's normally good practice to specify which properties should animate like so: `transition: background-color 0.25s;`.
2. We're defining a `gap: 10px` on the `.droppable` area. This is not recommended because RBD only takes the draggable element dimensions, padding and margin into account. Please remove that property and instead set `margin-bottom: 10px;` on the `.tvshow` class. 😃 

Here's a working example: https://codesandbox.io/s/rbd-issue-2086-forked-2g6dk?file=/styles/pages/index.js

Will close this issue for now, but please feel free to reopen if the issue persists. 👍

**Closed by danieldelcore** 2021-04-16 01:06 UTC
Labels: more information required
