### ISSUE TITLE
Dragging breaking on items below page fold.

### ISSUE THREAD

**Issue by jonathancherry** [atlassian/react-beautiful-dnd#487] opened 2018-05-02 23:48 UTC
All item droppable area below page fold isn't working for me. Using portal implementation. 

![untitled](https://user-images.githubusercontent.com/585153/39554526-3c8959f6-4e6b-11e8-89c3-2cff0163998d.gif)

Any ideas?

**Comment by alexreardon** [comment] 2018-05-03 07:30
I am unable to reproduce the issue. Can you please create a standalone example on codesandbox.io. I suspect you are using nested scroll containers which is currently not supported

**Comment by jonathancherry** [comment] 2018-05-03 08:47
I think it has something to do with the semantic-ui stylesheet

https://codesandbox.io/s/88n6j1xlnj

If you take body overflow-x: hidden off then it works. But this then breaks any layouts using pushable sidebars.

**Comment by pareshchouhan** [comment] 2018-05-09 03:13
Similar issue, let's say list has 30 items and you drag the 10th item then I am only able to place it at (10 - ith index) and (10 + jth index)  (for me i and j are 2,2 )

**Comment by alexreardon** [comment] 2018-05-10 04:13
If the draggable itself was a droppable this was fixed in #476 and is now released

**Closed by alexreardon** 2018-05-10 04:13 UTC
Labels: more information required
