### ISSUE TITLE
Drop Target Incorrect When Combine is Enabled

### ISSUE THREAD

**Issue by kruser** [atlassian/react-beautiful-dnd#1529] opened 2019-10-03 19:48 UTC
### Expected behavior
Only populate `snapshot.combineTargetFor` when appropriate

### Actual behavior
Opposite of expected, though intermittent.

### Steps to reproduce
1. start with your own demo here: https://react-beautiful-dnd.netlify.com/?path=/story/single-vertical-list--with-combine-enabled
2. Take the second to last element and drag it below and out of the context. Intermittantly when you come back up, the final element will have a `snapshot.combineTargetFor` even though the source isn't over or really near it. This take a little bit of playing with the throw it off. Maybe two or more times and coming back into the context from the side.

### Suggested solution?
🤷‍♂ 

### What version of `React` are you using?
16.8.6

### What version of `react-beautiful-dnd` are you running?
11.0.5

### What browser are you using?
Chrome 77

### Demo
See below, the second element has the style triggered by the `combineTargetFor` even though the draggable isn't over it.

![Screenshot 2019-10-03 at 2 41 42 PM](https://user-images.githubusercontent.com/2208700/66159011-ba2c0380-e5ec-11e9-97bb-dfd9c91cf765.png)

**Comment by alexreardon** [comment] 2019-10-09 01:07
Confirmed. It also exists in `12.0`

**Comment by alexreardon** [comment] 2019-10-09 01:26
#1487

**Comment by alexreardon** [comment] 2019-10-09 04:04
Fixed in `12.0.0-beta.5`

**Comment by alexreardon** [comment] 2019-10-09 04:04
Thanks for raising this one!

**Closed by alexreardon** 2019-10-09 04:04 UTC
Labels: bug 🐞, investigating 🕵️‍♂️

**Comment by sunnylittle** [comment] 2020-03-22 22:32
I'm also seeing an issue where `combineTargetFor` is null. I don't see anything in documentation where that would be expected. I don't have sandbox to show you unfortunately. 
But I have `isCombineEnabled` set, my list a a virtual list, everything else seems to be working as expected and the `combineWith` id is correct.
I'm on react-beautiful-dnd version 13.0.0. 
I don't know if this is an actual issue or if I should expect `combineTargetFor` to be null in certain cases.

**Comment by robcecil** [comment] 2020-08-12 16:54
> I'm also seeing an issue where `combineTargetFor` is null. I don't see anything in documentation where that would be expected. I don't have sandbox to show you unfortunately.
> But I have `isCombineEnabled` set, my list a a virtual list, everything else seems to be working as expected and the `combineWith` id is correct.
> I'm on react-beautiful-dnd version 13.0.0.
> I don't know if this is an actual issue or if I should expect `combineTargetFor` to be null in certain cases.

Are you dropping onto a separate list? Multi-list?

Does Combine work across lists?
