### ISSUE TITLE
Usage with react-router-dom Link as draggable item

### ISSUE THREAD

**Issue by apuntovanini** [atlassian/react-beautiful-dnd#482] opened 2018-04-30 15:28 UTC
### Expected behavior
Dragging a Link (react-router-dom), onDragEnd drops the item, while clicking the item surfs to new page.

### Actual behavior
Dragging a Link (react-router-dom), onDragEnd triggers the history push and goes to new page instead of dropping the item into the proper position

### Steps to reproduce
Occurs on mobile, ios, guess it is related to touchStart handling

Thanks!

**Comment by alexreardon** [comment] 2018-05-01 23:08
Can you please provide a stand alone example? Ideally on codesandbox.io

Here is our boilerplate: https://codesandbox.io/s/k260nyxq9v

**Comment by apuntovanini** [comment] 2018-05-02 17:11
Yep, here it is: https://codesandbox.io/s/r4r231nrqp

Some details though: it works properly on desktop, and also on mobile Safari apparently. Things get bad when I embed the whole thing in a WebView
You can try it at  https://expo.io/@apuntovanini/dnd-react-router

**Comment by alexreardon** [comment] 2018-05-03 07:33
I suspect that:

- the touch handlers are either not being passed through to the DOM node by react-router-dom
- it is clobbering the touch event handlers
- it is calling preventDefault onTouchStart

Whatever the case we are unable to ensure that the library passes through these props correctly as it is not in our control

**Comment by alexreardon** [comment] 2018-05-03 22:09
It looks like `Link` is passing through the props...

```js
return (
      <a {...props} onClick={this.handleClick} href={href} ref={innerRef} />
    );
```

https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js

**Comment by alexreardon** [comment] 2018-05-17 22:56
I am currently unable to reproduce this so i will close this for now. Please reopen if you have more information that can be actioned

Cheers!

**Closed by alexreardon** 2018-05-17 22:56 UTC
Labels: more information required
