### ISSUE TITLE
Dynamic Droppable Component not working when I was move other component child.

### ISSUE THREAD

**Issue by mehmetcan92** [atlassian/react-beautiful-dnd#1191] opened 2019-03-21 14:12 UTC
I will try explain my issue. First of all I'm trying  make formula designer component with React DND. I'm creating a Droppable area dynamically in the run time.  After that I'm moving the first created Droppable to a child of a component.But first created Droppable didn't work and I don't drop any draggable item. I keep the dynamic components in an object. I'm sharing structure data and image below.

Red squares  first created  droppable component and they have uniq Id but dont work.
Green squares  second created droppable component and they have uniq Id.So, Droppable components in the red square,were moved to the parent of the Droppable components in the Green square,

![image](https://user-images.githubusercontent.com/5290707/54753150-65e1a900-4bf1-11e9-9fec-66b8741f0782.png)

- first created  droppable component unrendered component data in object like that below. **when this objects rendered ,all of them work right .**
**main**:(3) [{…}, {…}, {…}]
  0:
  $$typeof: Symbol(react.element)
  key: null
  props:
  bracketsMouseDown: ƒ bracketsMouseDown(e, brackets)
  child: []
  context: {deviceSize: 4, platform: 3, language: 5, moduleId: 1, isEtx: false, …}
  customStyle: undefined
  depth: 2
  disabled: false
  dropMouseOutComponent: ƒ dropMouseOutComponent(e)
  dropMouseOverComponent: ƒ dropMouseOverComponent(e)
  droppableId: **"8225748a-1f6e-b7ec-cfbe-129a83beb64b"**
  errorText: ""
  helperText: ""
  isVisible: true
  newLine: false
  size: 3
  sizeFixed: false
  type: "Operands"
  __proto__: Object
  ref: null
  type: ƒ IIBComponent()
  _owner: null
  _store: {validated: true}
  _self: null
  _source: null
  __proto__: Object
  1: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
  2: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
  length: 3

- Second created  droppable component unrendered component data in object like that below and first created droppable  moved to  child  of second created component.Although all of the component's properties with the First created  id "8225748a-1f6e-b7ec-cfbe-129a83beb64b" are the same, this time does not work properly.

**main**:(3) [{…}, {…}, {…}]
0:
$$typeof: Symbol(react.element)
key: null
props:
bracketsMouseDown: ƒ bracketsMouseDown(e, brackets)
child: Array(3)
0:
$$typeof: Symbol(react.element)
key: null
props:
bracketsMouseDown: ƒ bracketsMouseDown(e, brackets)
child: []
context: {deviceSize: 4, platform: 3, language: 5, moduleId: 1, isEtx: false, …}
customStyle: []
depth: 3
disabled: false
dropMouseOutComponent: ƒ dropMouseOutComponent(e)
dropMouseOverComponent: ƒ dropMouseOverComponent(e)
droppableId: **"8225748a-1f6e-b7ec-cfbe-129a83beb64b"**
errorText: ""
helperText: ""
isVisible: true
newLine: false
size: 3
sizeFixed: false
type: "Operands"
__proto__: Object
ref: null
type: ƒ IIBComponent()
_owner: null
_store: {validated: false}
_self: null
_source: null
__proto__: Object
1: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
2: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
length: 3
__proto__: Array(0)
context: {deviceSize: 4, platform: 3, language: 5, moduleId: 1, isEtx: false, …}
customStyle: undefined
depth: 2
disabled: false
dropMouseOutComponent: ƒ dropMouseOutComponent(e)
dropMouseOverComponent: ƒ dropMouseOverComponent(e)
droppableId: "c3357156-3398-921e-86ea-92d752e09482"
errorText: ""
helperText: ""
isVisible: true
newLine: false
size: 3
sizeFixed: false
type: "Operands"
__proto__: Object
ref: null
type: ƒ IIBComponent()
_owner: null
_store: {validated: false}
_self: null
_source: null
__proto__: Object
1: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …}
2: {$$typeof: Symbol(react.element), type: ƒ, key: null, ref: null, props: {…}, …} 

But when I left the ** main ** array empty and set the data back on again, I discovered that it works correctly. By the way I use forceupdate() after this process.

Also  I'm have delete state button. when it click,it delete state for dynmaic droppable. I'm getting error below.Btw All droppable and draggable ids is unique.red squares all in one droppable component and they have uniq Id.

tiny-invariant.esm.js:11 
Uncaught Error: Invariant failed: Cannot unregister Droppable with id 8225748a-1f6e-b7ec-cfbe-129a83beb64b as as it is not registered
    at invariant (tiny-invariant.esm.js:11)

![image](https://user-images.githubusercontent.com/5290707/54756848-18b60500-4bfa-11e9-82ad-f788030071d7.png)

I have two question related to issues.
1.Why is Dynamic Droppable Component not working when I was move other component child ? Is it unsupported using or bug ? 
2. why I get such an error when I try to delete the component even though all IDs are unique  ? 

I examined same issues. Maybe your component doesn't support dynamic creation. In my opinion that this component cannot catch the differences in the DOM and is losing the Droppable component. That's why I  can't drop any draggable item.

Can you help me or do you have a different solution?

Thanks a lot

**Comment by beatelite** [comment] 2019-04-05 02:54
I have this same issue. 

I'm dynamically rendering a droppable list in a Material UI dialog modal.  I also have my draggables in a material UI drawer.

I can get them both to show up initially and can drag and drop between them. Once I DnD between the lists, and then I close the modal and try to click a new tab, I get the following errors : 

`Uncaught Error: Invariant failed: Cannot unregister Droppable with id placesTemplateList as as it is not registered` 

and 

`Invariant failed: Cannot unregister Droppable with id placesTemplateList as as it is not registered`

 The weird thing it ONLY happens once I do a drag between the lists. If I just click the modals and tabs and perform reordering on any list, I don't get any erorrs.  

I think it's because performing DnD between two dynamically rendered lists somehow registers them with RBDND. Once I click away to another tab, React renders the new tab content and removes the other one ( confirmed in react dev tools that the node with the list no longer exists in the DOM tree ). 

Not sure how to fix but I'm gutted as I've come so far with the app and this library. Hope we can resolve!

**Comment by beatelite** [comment] 2019-04-05 03:49
Ok, mine is fixed and may not be the same problem.

 I was using the same component (in the tab and in the modal) to render the droppable lists of draggables (which I thought would be fine because the draggables were unique). 

When I cloned the component into a new file, I gave it a different droppableID and used one in the modal and one in the tab. Now everything works!

**Comment by alexreardon** [comment] 2019-04-18 05:04
I am not sure if there is anything to action here. Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

I'll close this for now, but we can reopen if needed

**Closed by alexreardon** 2019-04-18 05:04 UTC
