### ISSUE TITLE
Error: Function Components cannot be given refs. 

### ISSUE THREAD

**Issue by pradeepravi-cse** [atlassian/react-beautiful-dnd#2087] opened 2021-02-10 09:00 UTC
### Expected behavior
Droppable should not throw any error

### Actual behavior
![image](https://user-images.githubusercontent.com/7976356/107487387-212bd600-6bac-11eb-9cef-ed0ccc68eba7.png)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/7976356/107487545-4ae4fd00-6bac-11eb-98cd-f759c45e6474.png)

### What version of `React` are you using?
"react": "^16.14.0"

### What version of `react-beautiful-dnd` are you running?
   "react-beautiful-dnd": "^13.0.0",

### What browser are you using?
Chrome

**Comment by danieldelcore** [comment] 2021-02-12 01:26
Hi there, would you be able to reproduce the issue in [codesandbox](https://codesandbox.io/s/new) for me to look at!

**Comment by pradeepravi-cse** [comment] 2021-02-12 05:10
@danieldelcore Please have a look at the [codesandbox](https://codesandbox.io/s/nostalgic-northcutt-zre0c)

**Comment by danieldelcore** [comment] 2021-02-15 03:43
Hi there, this seems to be an error with your use of `@material-ui/menu`. 

The wrapping menu element accepts an `anchorEl`, which `Menu` must be applying a ref to internally. 
In cases when you set `anchorEl` to `null` the component throws an error because the prop must be given a component at all times ([as per the documentation](https://material-ui.com/api/menu/)). 

A quick and hacky way I managed to fix this issue is by updating the props like so: 

```diff
<Menu
          id="simple-menu"
          anchorEl={anchorEl}
          keepMounted
          open={Boolean(anchorEl)}
          onClose={() => {
-            setAnchorEl(null);
+            setAnchorEl(() => {});
          }}
-          onBackdropClick={() => setAnchorEl(null)}
+         onBackdropClick={() => setAnchorEl(() => {})}
          className="clauseMenu"
>
``` 

Since this issue is related to usage of a third party libraries and not RBD itself, i'll close this issue for now. 

Thanks 😄

**Closed by danieldelcore** 2021-02-15 03:43 UTC
Labels: more information required, unconfirmed-bug
