### ISSUE TITLE
Disabling animations to solve performance issues?

### ISSUE THREAD

**Issue by shennan** [atlassian/react-beautiful-dnd#1563] opened 2019-10-25 16:12 UTC
I understand that this issue has been raised before in #387, but I feel like this needs looking at again. It can't be right that on a 13-inch, Late 2016 Macbook Pro it feels this jerky.

In the example below, there are only 29 draggables, with 8 possible droppable containers.

![2019-10-25 16 52 39](https://user-images.githubusercontent.com/1840398/67585731-15fb2f80-f748-11e9-9762-d9d81e8ea983.gif)

The draggable being dragged feels very far behind the mouse cursor. During these movements the FPS drops to between 17 and 28.

Are there any obvious ways to improve the FPS? I think the library is great and I found it pretty easy to implement - but this is currently blocking me from using it in production. Could dropping the sorting animations not improve the responsiveness?

**Comment by shennan** [comment] 2019-11-05 11:48
FYI have tried this with `v11.5.0` and the new `v12.0.0` with not much improvement to performance. I see the new Virtual Lists addition as negligible given that all items I'm using here operate within the viewpoint.

I'm using React `v16.10.2` also.

**Comment by pepijnolivier** [comment] 2019-12-17 21:50
[This video](https://egghead.io/lessons/react-optimize-performance-in-react-beautiful-dnd-with-shouldcomponentupdate-and-purecomponent), which is also linked in the readme, helped me a lot earlier today.
Especially the part where it prevents unnecessary re-renders in the item component.

After implementing `shouldComponentUpdate` on the list (as shown in the video), I also wrapped all of my items (which were functional components) in `React.memo`.

Definitely a noticable difference.

**Comment by danieldelcore** [comment] 2019-12-19 04:28
Hi @shennan, 
Thanks for raising this issue! 

Can you please create a standalone example on codesandbox.io using our boilerplate: https://codesandbox.io/s/k260nyxq9v

At first glance, it might be related to re-renders occuring in your react tree, when ever you drag your elements around. You can debug this using Chrome devtools by enabling 'Paint Flashing'. It will show where in your app rerenders are occuring. 

Let me know how that goes 👍 

Cheers!

**Comment by AlithAnar** [comment] 2019-12-19 10:29
Hi, we've got similar problem with FPS.

Using 'Paint Flahing' we've found many huge repaints while dragging item over. 
![alt text](https://tc3-img-dev.s3.eu-central-1.amazonaws.com/42a57364e958203aeaf930aae5ee3ab3dfffa20277d575372ec3db7d5976da00)

Hoverew using React 'Highlight Updates' tool, it looks like this:
![alt text](https://tc3-img-dev.s3.eu-central-1.amazonaws.com/95b52cd7667b00be079a228428d99628e561961b2695975acd15d06dfe4ddb5c)

We've put console.log's inside render methods and our lists and item renderers stays calm, without any unnecessary rerenders...

**Comment by alexreardon** [comment] 2020-01-06 05:14
Hi there!

Can you please create a standalone example on `codesandbox.io` using our boilerplate: https://codesandbox.io/s/k260nyxq9v

Without a standalone example, it is impossible for us to know if it is a library issue or not

Cheers!

**Comment by alexreardon** [comment] 2020-01-06 05:15
It looks like something in the react tree is rendering when it shouldn't

**Comment by alexreardon** [comment] 2020-01-10 01:00
I suspect you are re-rendering your list when something enters it.

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#recommended-droppable--performance-optimisation

The green flash for your whole app is concerning. Are you doing a setState in your drag drop context in a responder?

As Dan mentioned, we cannot assist too much without a reproducible example

**Comment by shennan** [comment] 2020-01-10 16:58
Apologies for the late reply @alexreardon. We moved onto react-dnd. Not quite as beautiful but we needed to get the feature out so we're not planning on returning to this anytime soon.

As @AlithAnar seems to have a similar issue; perhaps keep this open and see if they respond with an isolated example.

**Comment by AlithAnar** [comment] 2020-01-10 19:37
I will prepare example using rbdnd boilerplate on monday..

**Comment by mattpotato** [comment] 2021-01-07 13:34
I also had the same issue with multiple lists (using CRA + Chakra UI). But I noticed that the performance issues was minimal in production compared to development. Using React.memo still helped for development though.

**Comment by danieldelcore** [comment] 2021-01-12 09:14
Hey folks, will close this issue for now since this issue seems to be due to react re-renders. 
Feel free to re-open if you suspect a bug with RBD! 

Thanks to all for contributing to the discussion

**Closed by danieldelcore** 2021-01-12 09:14 UTC
Labels: more information required

**Comment by joe-gre** [comment] 2021-07-26 23:33
I'm seeing performance issues not due to rerenders of my components. I verified my component that contains the single Droppable is only rendered once when reordering. Here is a performance profile of reordering of a single list with only one Droppable and 33 list items: 
![image](https://user-images.githubusercontent.com/22748761/127072011-f98d6948-2aa8-487f-9dd6-15245bd75ab8.png)

You can see a number of Recalculate Style tasks that each take about 350 milliseconds. I'm not using any complex CSS selectors for the list or list items, just class selectors. It seems to be an issue with react-beautiful-dnd.

**Comment by nell209** [comment] 2021-10-02 01:17
Bumping this issue because performance is awful for me and it seems all of it is due to recalculate style by the b-dnd library which takes 1.8 seconds before the card itself becomes draggable:

My longest render is ~2ms and the remaining 7 are under 0.5 ms everything is memorized so no unnecessary renders

![image](https://user-images.githubusercontent.com/23680784/135699301-1fe6c1bd-b08c-4d60-8bb4-0e722e37f6bb.png)

![image](https://user-images.githubusercontent.com/23680784/135699357-e9f08d56-6519-43c5-b54a-dbf1970675be.png)
